#!/bin/sh

set -e

restart_oxend=

if [ "$1" = configure ]; then
    . /usr/share/debconf/confmodule
    db_get session-service-node/ip-address
    IP="$RET"
    db_get session-service-node/l2-provider
    L2="$RET"

    c=/etc/oxen/oxen.conf

    # The old oxen-service-node package used to have a diversion of oxen.conf, but it didn't work
    # properly and so we want to remove it to clean that up.
    if [ "$(dpkg-divert --listpackage $c)" = "oxen-service-node" ]; then
        dpkg-divert --no-rename --package oxen-service-node --remove $c
    fi

    # We also used to manage the file via ucf, but that caused more problems than it was worth as we
    # only make very small, and strictly required, edits to config, so just purge that record if it
    # exists:
    ucfr --force --purge session-service-node $c

    if ! [ -f $c ]; then
        cp /usr/share/oxend/oxen.conf $c
        restart_oxend=1
    fi

    # Since this is the service node metapackage, we want to always ensure that oxen.conf has the
    # service-node=1, service-node-public-ip=..., and l2-provider= (or l2-oxend=):

    if ! grep -q '^service_node=1' $c; then
        # Replace commented or uncommented `service_node=*` with `service-node=1` to turn on service
        # node mode.  Append to the end if not found.
        sed -i '/^#\?service-node=/{h;s/.*=.*/service-node=1/};${x;/^$/{s//service-node=1/;H};x}' $c
        restart_oxend=1
    fi

    # If there is no service-node-public-ip= then append one with the value asked during package
    # config:
    if ! grep -q '^service-node-public-ip=' $c; then
        echo "" >>$c
        echo "service-node-public-ip=$IP" >>$c
        restart_oxend=1
    fi

    # If there is neither l2-provider= nor l2-oxend= then we will append one, based on what was
    # asked during package config.  If either is already present then do nothing.
    if ! grep -q '^l2-\(oxend\|provider\)=' $c; then
        case "$L2" in
            "l2-oxend="*)
                restart_oxend=1
                first=1
                for x in $L2; do
                    if [ -n "$first" ]; then
                        echo "" >>$c
                        echo "$x" >>$c
                        first=
                    else
                        echo "l2-oxend=$x" >>$c
                    fi
                done
                ;;
            "")
                # Empty string means they explicit gave nothing, so we don't add anything and they
                # are on their own.
                ;;
            *)
                restart_oxend=1
                first=1
                for x in $L2; do
                    if [ -n "$first" ]; then
                        echo "" >>$c
                        first=
                    fi
                    echo "l2-provider=$x" >>$c
                done
                ;;
        esac
    fi
fi

#DEBHELPER#

# Debhelper doesn't do this here because the session-service-node package doesn't contain the service files:
if [ "$1" = "configure" ]; then
    if [ -d /run/systemd/system ] && [ -n "$restart_oxend" ]; then
        systemctl --system daemon-reload >/dev/null || true
        deb-systemd-invoke restart oxen-node.service || true
    fi
fi
